version: '3.7'

services:
  cantaloupe:
    image: mitlibraries/cantaloupe
    ports:
      - 8182:8182
    environment:
      HTTP_HTTP2_ENABLED: "true"
      HTTPS_HTTP2_ENABLED: "true"
      ENDPOINT_IIIF_CONTENT_DISPOSITION: none
      SOURCE_STATIC: S3Source
      S3SOURCE_ENDPOINT: http://minio:9000
      S3SOURCE_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3SOURCE_SECRET_KEY: ${S3_SECRET_ACCESS_KEY}
      S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME: "${S3_BUCKET_NAME}"
      S3SOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX: ''
      S3SOURCE_BASICLOOKUPSTRATEGY_PATH_SUFFIX: ''
      CACHE_SERVER_DERIVATIVE_ENABLED: "true"
      CACHE_SERVER_DERIVATIVE: S3Cache
      CACHE_SERVIER_DERIVATIVE_TTL_SECONDS: 0
      CACHE_SERVER_PURGE_MISSING: "true"
      CACHE_SERVER_WORKER_ENABLED: "true"
      S3CACHE_ENDPOINT: http://minio:9000
      S3CACHE_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3CACHE_SECRET_KEY: ${S3_SECRET_ACCESS_KEY}
      S3CACHE_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3CACHE_OBJECT_KEY_PREFIX: cache
      LOG_APPLICATION_LEVEL: warn
      LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
      PROCESSOR_FALLBACK: Java2dProcessor
      OVERLAYS_STRATEGY: BasicStrategy
