apiVersion: v1
kind: Secret
metadata:
  name: document-db
type: Opaque
data:
  connection-string: "{{ .Values.docdb.connectionString }}"
  username: "{{ .Values.docdb.username }}"
  password: "{{ .Values.docdb.password }}"