apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--frontend
  labels:
    {{- include "articleHosting.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
        {{- include "articleHosting.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
          {{- include "articleHosting.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: app
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: document-db 
                  key: connection-string
            - name: DOCDB_USER
              valueFrom:
                secretKeyRef:
                  name: document-db
                  key: username
            - name: DOCDB_PASS
              valueFrom:
                secretKeyRef:
                  name: document-db
                  key: password
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: bucketname
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: accesskey
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: secretkey
            - name: APP_HOSTNAME
              value: "{{ .Values.hostname }}"
          #resources:
          #  limits:
          #    memory: "1300Mi"
          #    cpu: "800m"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: http