apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--frontend
  labels:
    {{- include "articleHosting.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
        {{- include "articleHosting.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
          {{- include "articleHosting.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: app
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: document_db 
                  key: connection_string
          resources:
            limits:
              memory: "1536Mi"
              cpu: "800m"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: http