apiVersion: v1
kind: Secret
metadata:
  name: s3-secrets
type: Opaque
data:
  bucketname: "{{ .Values.s3.bucketname }}"
  accesskey: "{{ .Values.s3.accesskey }}"
  secretkey: "{{ .Values.s3.secretkey }}"