apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--frontend
  labels:
    {{- include "articleHosting.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  #type: LoadBalancer
  type: ClusterIP
  ports:
    - targetPort: 8000
      port: 80
      protocol: TCP
      name: http
    - targetPort: 8001
      port: 443
      name: https
  selector:
      {{- include "articleHosting.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
