name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  frontend:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          make IMAGE_TAG=${IMAGE_TAG} TARGET=prod build
      - name: Lint
        run: |
          make IMAGE_TAG=${IMAGE_TAG} lint
      - name: Test
        run: |
          make IMAGE_TAG=${IMAGE_TAG} test
      - name: e2e tests
        run: |
          .github/e2e.sh
      - name: Push Docker image
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
          docker push liberoadmin/article-hosting:${IMAGE_TAG}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          aws --region=us-east-1 eks update-kubeconfig --name hive-eks--curie
          helm upgrade -i article-hosting--prod \
            --set images.frontend.tag=${IMAGE_TAG} \
            --set hostname=article.hosting \
            --set certificate=arn:aws:acm:us-east-1:540790251273:certificate/d52726d1-6667-4d67-a9ff-c8abd2f9906f \
            --set docdb.connectionString=${{ secrets.CONNECTION_STRING }} \
            --set docdb.username=${{ secrets.DOCDB_USERNAME }} \
            --set docdb.password=${{ secrets.DOCDB_PASSWORD }} \
            --wait \
            --force \
            helm/article-hosting
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Notify Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: article-hosting-general
          status: FAILED
          color: danger
